EM2005_with_stats_exp2

fprintf('\n\n');

OG_only = logical(blocks(:, 1));
focality = logical(blocks(:, 2));
emphasis = logical(blocks(:, 3));
block_id = blocks(:, 10);
first_and_last_blocks = block_id == 1 | block_id == 4;

sem = @(x) std(x) / sqrt(length(x));

% OG accuracy PM vs. no PM
OG_acc = blocks(:, 5);
fprintf(['Accuracy on the ongoing task was near ceiling in all simulations (M = %.2f +- %.2f %%), ' ...
    'both in the presence of a PM instruction (M = %.2f +- %.2f %%) as well as in its absence (%.2f +- %.2f %%)\n'], ...
    mean(OG_acc(:)), sem(OG_acc(:)), ...
    mean(OG_acc(~OG_only)), sem(OG_acc(~OG_only)), ...
    mean(OG_acc(OG_only)), sem(OG_acc(OG_only)));

% OG accuracy 4 blocks -- nonfocal only, focal only
[p, table] = anovan(OG_acc(~focality & first_and_last_blocks & ~OG_only), {block_id(~focality & first_and_last_blocks & ~OG_only)}, 'model','full', 'display', 'off');
fprintf(['Over the four PM blocks, OG accuracy remained near ceiling ', ...
    'when the target was nonfocal (Ms = %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%; ', ...
    'comparison between first and last block, F = %f, p = %f) '], ...
    mean(OG_acc(~OG_only & ~focality & block_id == 1)), sem(OG_acc(~OG_only & ~focality & block_id == 1)), ...
    mean(OG_acc(~OG_only & ~focality & block_id == 2)), sem(OG_acc(~OG_only & ~focality & block_id == 2)), ...
    mean(OG_acc(~OG_only & ~focality & block_id == 3)), sem(OG_acc(~OG_only & ~focality & block_id == 3)), ...
    mean(OG_acc(~OG_only & ~focality & block_id == 4)), sem(OG_acc(~OG_only & ~focality & block_id == 4)), ...
    table{2,6}, p(1));
[p, table] = anovan(OG_acc(focality & first_and_last_blocks & ~OG_only), {block_id(focality & first_and_last_blocks & ~OG_only)}, 'model','full', 'display', 'off');
fprintf(['and when the target was focal ', ...
    '(Ms = %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%; ', ...
    'comparison between first and last block, F = %f, p = %f).\n'], ...
    mean(OG_acc(~OG_only & focality & block_id == 1)), sem(OG_acc(~OG_only & focality & block_id == 1)), ...
    mean(OG_acc(~OG_only & focality & block_id == 2)), sem(OG_acc(~OG_only & focality & block_id == 2)), ...
    mean(OG_acc(~OG_only & focality & block_id == 3)), sem(OG_acc(~OG_only & focality & block_id == 3)), ...
    mean(OG_acc(~OG_only & focality & block_id == 4)), sem(OG_acc(~OG_only & focality & block_id == 4)), ...
    table{2,6}, p(1));

fprintf('\n');

% OG RT focality
OG_RTs = blocks(:, 4) * RT_slope + RT_intercept;
[p, table] = anovan(OG_RTs(~OG_only), {focality(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['In the presence of a PM instruction, ', ...
    'ongoing RTs were significantly faster when the PM target was focal (M = %.2f +- %.2f ms) ', ...
    'compared to when it was nonfocal (M = %.2f +- %.2f ms; F = %f, p = %e).\n'], ... 
    mean(OG_RTs(~OG_only & focality)), sem(OG_RTs(~OG_only & focality)), ...
    mean(OG_RTs(~OG_only & ~focality)), sem(OG_RTs(~OG_only & ~focality)), ...
    table{2,6}, p(1));


% OG RT 4 blocks -- nonfocal only, focal only
[p, table] = anovan(OG_RTs(~focality & first_and_last_blocks & ~OG_only), {block_id(~focality & first_and_last_blocks & ~OG_only)}, 'model','full', 'display', 'off');
fprintf(['Over the four PM blocks, ongoing RTs became faster (i.e. the OG cost decreased) ', ...
    'when the target was nonfocal (Ms = %.2f +- %.2f ms, %.2f +- %.2f ms, %.2f +- %.2f ms, %.2f +- %.2f ms; ', ...
    'comparison between first and last block, F = %f, p = %f) '], ...
    mean(OG_RTs(~OG_only & ~focality & block_id == 1)), sem(OG_RTs(~OG_only & ~focality & block_id == 1)), ...
    mean(OG_RTs(~OG_only & ~focality & block_id == 2)), sem(OG_RTs(~OG_only & ~focality & block_id == 2)), ...
    mean(OG_RTs(~OG_only & ~focality & block_id == 3)), sem(OG_RTs(~OG_only & ~focality & block_id == 3)), ...
    mean(OG_RTs(~OG_only & ~focality & block_id == 4)), sem(OG_RTs(~OG_only & ~focality & block_id == 4)), ...
    table{2,6}, p(1));
[p, table] = anovan(OG_RTs(focality & first_and_last_blocks & ~OG_only), {block_id(focality & first_and_last_blocks & ~OG_only)}, 'model','full', 'display', 'off');
fprintf(['but remained relatively stable when the target was focal, although there was a small but significant decrease in OG RTs over time (Ms = %.2f +- %.2f ms, %.2f +- %.2f ms, %.2f +- %.2f ms, %.2f +- %.2f ms; ', ...
    'comparison between first and last block, F = %f, p = %f).\n'], ...
    mean(OG_RTs(~OG_only & focality & block_id == 1)), sem(OG_RTs(~OG_only & focality & block_id == 1)), ...
    mean(OG_RTs(~OG_only & focality & block_id == 2)), sem(OG_RTs(~OG_only & focality & block_id == 2)), ...
    mean(OG_RTs(~OG_only & focality & block_id == 3)), sem(OG_RTs(~OG_only & focality & block_id == 3)), ...
    mean(OG_RTs(~OG_only & focality & block_id == 4)), sem(OG_RTs(~OG_only & focality & block_id == 4)), ...
    table{2,6}, p(1));

fprintf('\n');

% PM hit rate 4 blocks -- nonfocal only, focal only
PM_hit = blocks(:, 7);
[p, table] = anovan(PM_hit(~focality & first_and_last_blocks & ~OG_only), {block_id(~focality & first_and_last_blocks & ~OG_only)}, 'model','full', 'display', 'off');
fprintf(['Over the four PM blocks, PM hit rates decreased ', ...
    'when the target was nonfocal (Ms = %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%; ', ...
    'comparison between first and last block, F = %f, p = %f) '], ...
    mean(PM_hit(~OG_only & ~focality & block_id == 1)), sem(PM_hit(~OG_only & ~focality & block_id == 1)), ...
    mean(PM_hit(~OG_only & ~focality & block_id == 2)), sem(PM_hit(~OG_only & ~focality & block_id == 2)), ...
    mean(PM_hit(~OG_only & ~focality & block_id == 3)), sem(PM_hit(~OG_only & ~focality & block_id == 3)), ...
    mean(PM_hit(~OG_only & ~focality & block_id == 4)), sem(PM_hit(~OG_only & ~focality & block_id == 4)), ...
    table{2,6}, p(1));
[p, table] = anovan(PM_hit(focality & first_and_last_blocks & ~OG_only), {block_id(focality & first_and_last_blocks & ~OG_only)}, 'model','full', 'display', 'off');
fprintf(['but remained relatively stable when the target was focal ', ...
    '(Ms = %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%, %.2f +- %.2f %%; ', ...
    'comparison between first and last block, F = %f, p = %f).\n'], ...
    mean(PM_hit(~OG_only & focality & block_id == 1)), sem(PM_hit(~OG_only & focality & block_id == 1)), ...
    mean(PM_hit(~OG_only & focality & block_id == 2)), sem(PM_hit(~OG_only & focality & block_id == 2)), ...
    mean(PM_hit(~OG_only & focality & block_id == 3)), sem(PM_hit(~OG_only & focality & block_id == 3)), ...
    mean(PM_hit(~OG_only & focality & block_id == 4)), sem(PM_hit(~OG_only & focality & block_id == 4)), ...
    table{2,6}, p(1));
