EM2005_with_stats_exp3

fprintf('\n\n');

OG_only = logical(subjects(:, 1));
focality = logical(subjects(:, 2));
targets = subjects(:, 9);

sem = @(x) std(x) / sqrt(length(x));

% OG accuracy PM vs. no PM
OG_acc = subjects(:, 5);
fprintf(['Accuracy on the ongoing task was lower compred to the previous simulations (M = %.2f +- %.2f %%) ' ...
    'due to the decreased signal-to-noise ratio in the S-R pathways. This reflects the increased difficulty of the task ', ...
    'that Einstein et al. used in this experiment and accounts for the relatively poor OG performance. ', ...
    'This accuracy level was similar in the presence of a PM instruction (M = %.2f +- %.2f %%) ', ...
    'as well as in its absence (%.2f +- %.2f %%)\n'], ...
    mean(OG_acc(:)), sem(OG_acc(:)), ...
    mean(OG_acc(~OG_only)), sem(OG_acc(~OG_only)), ...
    mean(OG_acc(OG_only)), sem(OG_acc(OG_only)));

% OG accuracy targets
[p, table] = anovan(OG_acc(~OG_only), {targets(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['In the presence of a PM instruction, ', ...
    'ongoing accuracy was relatively similar between the case of a single focal target (M = %.2f +- %.2f %%) ', ...
    'and the case of six focal targets (M = %.2f +- %.2f %%; F = %f, p = %f), although the difference was significant, ', ...
    'with the OG accuracy being slightly lower in the six-target condition.\n'], ... 
    mean(OG_acc(~OG_only & targets == 1)), sem(OG_acc(~OG_only & targets == 1)), ...
    mean(OG_acc(~OG_only & targets == 6)), sem(OG_acc(~OG_only & targets == 6)), ...
    table{2,6}, p(1));

fprintf('\n');

% OG RT targets
OG_RTs = subjects(:, 4) * RT_slope + RT_intercept;
[p, table] = anovan(OG_RTs(~OG_only), {targets(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['In the presence of a PM instruction, ', ...
    'ongoing RTs were significantly faster when there was a single focal target (M = %.2f +- %.2f ms) ', ...
    'compared to when there were six focal targets (M = %.2f +- %.2f ms; F = %f, p = %f).\n'], ... 
    mean(OG_RTs(~OG_only & targets == 1)), sem(OG_RTs(~OG_only & targets == 1)), ...
    mean(OG_RTs(~OG_only & targets == 6)), sem(OG_RTs(~OG_only & targets == 6)), ...
    table{2,6}, p(1));

fprintf('\n');

% PM hit rate focality
PM_hit = subjects(:, 7);
[p, table] = anovan(PM_hit(~OG_only), {targets(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['PM hit rates were relatively constant when there was a single focal target (M = %.2f +- %.2f %%) ', ...
    'compared to when there were six focal targets (M = %.2f +- %.2f %%; F = %f, p = %f).\n'], ... 
    mean(PM_hit(~OG_only & targets == 1)), sem(PM_hit(~OG_only & targets == 1)), ...
    mean(PM_hit(~OG_only & targets == 6)), sem(PM_hit(~OG_only & targets == 6)), ...
    table{2,6}, p(1));

