EM2005_with_stats_exp4

fprintf('\n\n');

OG_only = logical(subjects(:, 1));
monitoring = logical(subjects(:, 3));

sem = @(x) std(x) / sqrt(length(x));

% OG accuracy PM vs. no PM
OG_acc = subjects(:, 5);
fprintf(['Accuracy on the ongoing task similar to the previous simulation and lower than the former two (M = %.2f +- %.2f %%) ' ...
    'due to the decreased signal-to-noise ratio in the S-R pathways. This reflects the increased difficulty of the task ', ...
    'that Einstein et al. used in this experiment and accounts for the relatively poor OG performance. ', ...
    'This accuracy level was similar in the presence of a PM instruction (M = %.2f +- %.2f %%) ', ...
    'as well as in its absence (%.2f +- %.2f %%)\n'], ...
    mean(OG_acc(:)), sem(OG_acc(:)), ...
    mean(OG_acc(~OG_only)), sem(OG_acc(~OG_only)), ...
    mean(OG_acc(OG_only)), sem(OG_acc(OG_only)));

% OG accuracy targets
[p, table] = anovan(OG_acc(~OG_only), {monitoring(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['In the presence of a PM instruction, ', ...
    'ongoing accuracy was relatively similar for runs that had high OG costs (presumably reflecting high-monitoring strategies; M = %.2f +- %.2f %%) ', ...
    'and runs with low OG costs (presumably reflecting a low-monitoring strategies; M = %.2f +- %.2f %%; F = %f, p = %f), although there was a notable though insignificant ', ...
    'difference, with low monitors showing a better OG accuracy.\n'], ... 
    mean(OG_acc(~OG_only & monitoring)), sem(OG_acc(~OG_only & monitoring)), ...
    mean(OG_acc(~OG_only & ~monitoring)), sem(OG_acc(~OG_only & ~monitoring)), ...
    table{2,6}, p(1));

fprintf('\n');

% OG RT monitoring
OG_RTs = subjects(:, 4) * RT_slope + RT_intercept;
[p, table] = anovan(OG_RTs(~OG_only), {monitoring(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['In the presence of a PM instruction, ', ...
    'ongoing RTs were significantly slower for high-monitors (M = %.2f +- %.2f ms) ', ...
    'compared to low-monitors (M = %.2f +- %.2f ms; F = %f, p = %e). ', ...
    'This is expected and follows directly from the way we separated the runs by inferring monitoring strategy from OG cost.\n'], ... 
    mean(OG_RTs(~OG_only & monitoring)), sem(OG_RTs(~OG_only & monitoring)), ...
    mean(OG_RTs(~OG_only & ~monitoring)), sem(OG_RTs(~OG_only & ~monitoring)), ...
    table{2,6}, p(1));

fprintf('\n');

% PM hit rate monitoring
PM_hit = subjects(:, 7);
[p, table] = anovan(PM_hit(~OG_only), {monitoring(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['PM hit rates were relatively constant for high-monitors (M = %.2f +- %.2f %%) ', ...
    'compared to low-monitors (M = %.2f +- %.2f %%; F = %f, p = %f).\n'], ... 
    mean(PM_hit(~OG_only & monitoring)), sem(PM_hit(~OG_only & monitoring)), ...
    mean(PM_hit(~OG_only & ~monitoring)), sem(PM_hit(~OG_only & ~monitoring)), ...
    table{2,6}, p(1));



