B2010_with_stats

fprintf('\n\n');

OG_only = logical(subjects(:, 1));
focality = logical(subjects(:, 2));
capacity = logical(subjects(:, 3));

sem = @(x) std(x) / sqrt(length(x));
nansem = @(x) nanstd(x) / sqrt(length(x));

% PM hit rate capacity
PM_hit = subjects(:, 7);
[p, table] = anovan(PM_hit(~OG_only), {capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['PM hit rates were the relatively constant for high-WM runs (M = %.2f +- %.2f %%) ', ...
    'compared to low-WM runs (M = %.2f +- %.2f %%; F = %f, p = %f).\n'], ... 
    mean(PM_hit(~OG_only & capacity)), sem(PM_hit(~OG_only & capacity)), ...
    mean(PM_hit(~OG_only & ~capacity)), sem(PM_hit(~OG_only & ~capacity)), ...
    table{2,6}, p(1));

% PM hit rate focality X capacity
[p, table] = anovan(PM_hit(~OG_only & focality), {capacity(~OG_only & focality)}, 'model','full', 'display', 'off');
fprintf(['This was true both for focal targets (%.2f +- %.2f %% for high-WM vs. ', ...
    '%.2f +- %.2f %% for low-WM; F = %f, p = %f) '], ...
    mean(PM_hit(~OG_only & focality & capacity)), sem(PM_hit(~OG_only & focality & capacity)), ...
    mean(PM_hit(~OG_only & focality & ~capacity)), sem(PM_hit(~OG_only & focality & ~capacity)), ...
    table{2,6}, p(1));
[p, table] = anovan(PM_hit(~OG_only & capacity), {focality(~OG_only & capacity)}, 'model','full', 'display', 'off');
fprintf(['as well as for nonfocal targets (%.2f +- %.2f %% for high-WM vs. ', ...
    '%.2f +- %.2f %% for low-WM; F = %f, p = %f).\n'], ...
    mean(PM_hit(~OG_only & ~focality & capacity)), sem(PM_hit(~OG_only & ~focality & capacity)), ...
    mean(PM_hit(~OG_only & ~focality & ~capacity)), sem(PM_hit(~OG_only & ~focality & ~capacity)), ...
    table{2,6}, p(1));

fprintf('\n');

% PM RTs capacity
first_PM_RTs = subjects(:, 10) * PM_RT_slope + PM_RT_intercept;
[p, table] = anovan(first_PM_RTs(~OG_only), {capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['First-target PM RTs were similar for high-WM runs (M = %.2f +- %.2f ms) ', ...
    'compared to low-WM runs (M = %.2f +- %.2f ms; F = %f, p = %f).\n'], ... 
    nanmean(first_PM_RTs(~OG_only & capacity)), nansem(first_PM_RTs(~OG_only & capacity)), ...
    nanmean(first_PM_RTs(~OG_only & ~capacity)), nansem(first_PM_RTs(~OG_only & ~capacity)), ...
    table{2,6}, p(1));

% PM hit rate focality X capacity
[p, table] = anovan(first_PM_RTs(~OG_only & focality), {capacity(~OG_only & focality)}, 'model','full', 'display', 'off');
fprintf(['This was also true for focal targets (%.2f +- %.2f ms for high-WM vs. ', ...
    '%.2f +- %.2f ms for low-WM; F = %f, p = %f) '], ...
    nanmean(first_PM_RTs(~OG_only & focality & capacity)), nansem(first_PM_RTs(~OG_only & focality & capacity)), ...
    nanmean(first_PM_RTs(~OG_only & focality & ~capacity)), nansem(first_PM_RTs(~OG_only & focality & ~capacity)), ...
    table{2,6}, p(1));
[p, table] = anovan(first_PM_RTs(~OG_only & capacity), {focality(~OG_only & capacity)}, 'model','full', 'display', 'off');
fprintf(['as well as for nonfocal targets (%.2f +- %.2f ms for high-WM vs. ', ...
    '%.2f +- %.2f ms for low-WM; F = %f, p = %f). ', ...
    'For nonfocal targets, there was a notable though insignificant difference, with high-WM runs showing slightly faster RTs than low-WM runs.\n'], ...
    nanmean(first_PM_RTs(~OG_only & ~focality & capacity)), nansem(first_PM_RTs(~OG_only & ~focality & capacity)), ...
    nanmean(first_PM_RTs(~OG_only & ~focality & ~capacity)), nansem(first_PM_RTs(~OG_only & ~focality & ~capacity)), ...
    table{2,6}, p(1));

