B2010_with_stats

fprintf('\n\n');

OG_only = logical(subjects(:, 1));
focality = logical(subjects(:, 2));
capacity = logical(subjects(:, 3));

sem = @(x) std(x) / sqrt(length(x));
nansem = @(x) nanstd(x) / sqrt(length(x));

% OG accuracy PM vs. No PM
OG_acc = subjects(:, 5);
fprintf(['Accuracy on the ongoing task was near ceiling in all simulations (M = %.2f +- %.2f %%), ' ...
    'both in the presence of a PM instruction (M = %.2f +- %.2f %%) as well as in its absence (%.2f +- %.2f %%)\n'], ...
    mean(OG_acc(:)), sem(OG_acc(:)), ...
    mean(OG_acc(~OG_only)), sem(OG_acc(~OG_only)), ...
    mean(OG_acc(OG_only)), sem(OG_acc(OG_only)));

fprintf('\n');

% OG RT PM vs No PM
OG_RTs = subjects(:, 4) * RT_slope + RT_intercept;
[p, table] = anovan(OG_RTs, {OG_only}, 'model','full', 'display', 'off');
fprintf(['Ongoing RTs were slower in the presence of a PM instruction (M = %.2f +- %.2f ms), ', ...
    'compared to performing the OG task alone (M = %.2f +- %.2f ms; F = %f, p = %e)\n'], ...
    mean(OG_RTs(~OG_only)), sem(OG_RTs(~OG_only)), ...
    mean(OG_RTs(OG_only)), sem(OG_RTs(OG_only)), ...
    table{2,6}, p(1));

% OG RT focality
[p, table] = anovan(OG_RTs(~OG_only), {focality(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['In the presence of a PM instruction, ', ...
    'ongoing RTs were significantly faster when the PM target was focal (M = %.2f +- %.2f ms) ', ...
    'compared to when it was nonfocal (M = %.2f +- %.2f ms; F = %f, p = %e).\n'], ... 
    mean(OG_RTs(~OG_only & focality)), sem(OG_RTs(~OG_only & focality)), ...
    mean(OG_RTs(~OG_only & ~focality)), sem(OG_RTs(~OG_only & ~focality)), ...
    table{2,6}, p(1));

% OG RT WM capacity
[p, table] = anovan(OG_RTs(~OG_only), {capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['Also in the presence of a PM instruction, ', ...
    'there was no significant difference between OG RTs on runs simulating a low WM capacity (or low WM bias; M = %.2f +- %.2f ms) ', ...
    'and runs simulating a high WM capacity (or high WM bias; M = %.2f +- %.2f ms; F = %f, p = %e).\n'], ... 
    mean(OG_RTs(~OG_only & ~capacity)), sem(OG_RTs(~OG_only & ~capacity)), ...
    mean(OG_RTs(~OG_only & capacity)), sem(OG_RTs(~OG_only & capacity)), ...
    table{2,6}, p(1));


fprintf('\n');


% PM hit rate focality
PM_hit = subjects(:, 7);
[p, table] = anovan(PM_hit(~OG_only), {focality(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['PM hit rates were significantly higher when the PM target was focal (M = %.2f +- %.2f %%) ', ...
    'compared to when it was nonfocal (M = %.2f +- %.2f %%; F = %f, p = %e).\n'], ... 
    mean(PM_hit(~OG_only & focality)), sem(PM_hit(~OG_only & focality)), ...
    mean(PM_hit(~OG_only & ~focality)), sem(PM_hit(~OG_only & ~focality)), ...
    table{2,6}, p(1));

% PM hit rate capacity
[p, table] = anovan(PM_hit(~OG_only), {capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['PM hit rates were significantly higher for high-WM runs (M = %.2f +- %.2f %%) ', ...
    'compared to low-WM runs (M = %.2f +- %.2f %%; F = %f, p = %f).\n'], ... 
    mean(PM_hit(~OG_only & capacity)), sem(PM_hit(~OG_only & capacity)), ...
    mean(PM_hit(~OG_only & ~capacity)), sem(PM_hit(~OG_only & ~capacity)), ...
    table{2,6}, p(1));

% PM hit rate focality X capacity
[p, table] = anovan(PM_hit(~OG_only), {focality(~OG_only) capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf('There was a significant interaction between these two effects (F = %f, p = %f).\n', ...
    table{4,6}, p(3));
[p, table] = anovan(PM_hit(~OG_only & focality), {capacity(~OG_only & focality)}, 'model','full', 'display', 'off');
fprintf(['Specifically, for focal targets, the WM capacity was irrelevant and PM hit rates were near ceiling ', ...
    'both when the WM capacity was high (M = %.2f +- %.2f %%) ', ...
    'or low (M = %.2f +- %.2f %%; F = %f, p = %f).\n'], ...
    mean(PM_hit(~OG_only & focality & capacity)), sem(PM_hit(~OG_only & focality & capacity)), ...
    mean(PM_hit(~OG_only & focality & ~capacity)), sem(PM_hit(~OG_only & focality & ~capacity)), ...
    table{2,6}, p(1));
[p, table] = anovan(PM_hit(~OG_only & capacity), {focality(~OG_only & capacity)}, 'model','full', 'display', 'off');
fprintf(['For nonfocal targets, however, PM hit rates were significantly higher ', ...
    'when the WM capacity was high (M = %.2f +- %.2f %%), ', ...
    'compared to when it was low (M = %.2f +- %.2f %%; F = %f, p = %f).\n'], ...
    mean(PM_hit(~OG_only & ~focality & capacity)), sem(PM_hit(~OG_only & ~focality & capacity)), ...
    mean(PM_hit(~OG_only & ~focality & ~capacity)), sem(PM_hit(~OG_only & ~focality & ~capacity)), ...
    table{2,6}, p(1));


fprintf('\n');

% PM RTs focality
first_PM_RTs = subjects(:, 10) * PM_RT_slope + PM_RT_intercept;
[p, table] = anovan(first_PM_RTs(~OG_only), {focality(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['PM RTs on the first presented target item were significantly faster when the PM target was focal (M = %.2f +- %.2f ms) ', ...
    'compared to when it was nonfocal (M = %.2f +- %.2f ms; F = %f, p = %e).\n'], ... 
    nanmean(first_PM_RTs(~OG_only & focality)), nansem(first_PM_RTs(~OG_only & focality)), ...
    nanmean(first_PM_RTs(~OG_only & ~focality)), nansem(first_PM_RTs(~OG_only & ~focality)), ...
    table{2,6}, p(1));

% PM RTs capacity
[p, table] = anovan(first_PM_RTs(~OG_only), {capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf(['First-target PM RTs were notably although not significantly faster for high-WM runs (M = %.2f +- %.2f ms) ', ...
    'compared to low-WM runs (M = %.2f +- %.2f ms; F = %f, p = %f).\n'], ... 
    nanmean(first_PM_RTs(~OG_only & capacity)), nansem(first_PM_RTs(~OG_only & capacity)), ...
    nanmean(first_PM_RTs(~OG_only & ~capacity)), nansem(first_PM_RTs(~OG_only & ~capacity)), ...
    table{2,6}, p(1));

% PM hit rate focality X capacity
[p, table] = anovan(first_PM_RTs(~OG_only), {focality(~OG_only) capacity(~OG_only)}, 'model','full', 'display', 'off');
fprintf('There was a significant interaction between these two effects (F = %f, p = %f).\n', ...
    table{4,6}, p(3));
[p, table] = anovan(first_PM_RTs(~OG_only & focality), {capacity(~OG_only & focality)}, 'model','full', 'display', 'off');
fprintf(['Specifically, for focal targets, the WM capacity was irrelevant and first-target PM RTs were near ceiling ', ...
    'both when the WM capacity was high (M = %.2f +- %.2f ms) ', ...
    'or low (M = %.2f +- %.2f ms; F = %f, p = %f).\n'], ...
    nanmean(first_PM_RTs(~OG_only & focality & capacity)), nansem(first_PM_RTs(~OG_only & focality & capacity)), ...
    nanmean(first_PM_RTs(~OG_only & focality & ~capacity)), nansem(first_PM_RTs(~OG_only & focality & ~capacity)), ...
    table{2,6}, p(1));
[p, table] = anovan(first_PM_RTs(~OG_only & capacity), {focality(~OG_only & capacity)}, 'model','full', 'display', 'off');
fprintf(['For nonfocal targets, however, first-target PM RTs were significantly faster ', ...
    'when the WM capacity was high (M = %.2f +- %.2f ms), ', ...
    'compared to when it was low (M = %.2f +- %.2f ms; F = %f, p = %e).\n'], ...
    nanmean(first_PM_RTs(~OG_only & ~focality & capacity)), nansem(first_PM_RTs(~OG_only & ~focality & capacity)), ...
    nanmean(first_PM_RTs(~OG_only & ~focality & ~capacity)), nansem(first_PM_RTs(~OG_only & ~focality & ~capacity)), ...
    table{2,6}, p(1));

