FIGURE_EXP7

fprintf('\n\n');

OG_only = logical(subjects(:, 1));
focality = logical(subjects(:, 2));
targets = subjects(:, 9);

sem = @(x) std(x) / sqrt(length(x));

% Third task -- targets over time
IT_acc_targets_first = IT_tar_hits(:, 1);
IT_acc_targets_last = IT_tar_hits(:, blocks);
[p, table] = anovan([IT_acc_targets_first; IT_acc_targets_last], {[ones(length(IT_acc_targets_first), 1); zeros(length(IT_acc_targets_last), 1)]}, 'model','full', 'display', 'off');
fprintf(['Accuracy on the third task was near ceiling on items that were targets ', ...
    'during the PM instruction (M = %.2f +- %.2f %%) ', ...
    'and remained stable during all blocks ', ...
    '(%.2f +- %.2f %% in the first block vs. %.2f +- %.2f %% in the last block, F = %f, p = %f).\n'], ...
    mean(IT_tar_hits(:)), sem(IT_tar_hits(:)), ...
    mean(IT_acc_targets_first), sem(IT_acc_targets_first), ...
    mean(IT_acc_targets_last), sem(IT_acc_targets_last), ...
    table{2,6}, p(1));

% Third task -- commission errors over time
IT_comm_errors_first = IT_tar_pm_hits(:, 1);
IT_comm_errors_last = IT_tar_pm_hits(:, blocks);
[p, table] = anovan([IT_comm_errors_first; IT_comm_errors_last], {[ones(length(IT_comm_errors_first), 1); zeros(length(IT_comm_errors_last), 1)]}, 'model','full', 'display', 'off');
fprintf(['Commission errors were negligible (M = %.2f +- %.2f) across all blocks ', ...
    '(M = %.2f +- %.2f %% in the first block vs. M = %.2f +- %.2f %% in the last block; ', ...
    'F = %f, p = %f).\n'], ...
    mean(IT_tar_pm_hits(:)), sem(IT_tar_pm_hits(:)), ...
    mean(IT_comm_errors_first), sem(IT_comm_errors_first), ...
    mean(IT_comm_errors_last), sem(IT_comm_errors_last), ...
    table{2,6}, p(1));

fprintf('\n');


% Third task RTs -- targets vs non-targets
[p, table] = anovan([IT_target_RTs(:); IT_nontarget_RTs(:)], {[ones(length(IT_target_RTs(:)), 1); zeros(length(IT_nontarget_RTs(:)), 1)]}, 'model','full', 'display', 'off');
fprintf(['RTs on the third task were the same for items that were previously targets during the PM block (M = %.2f +- %.2f ms) ', ...
    'compared to items that were never targets (%.2f +- %.2f ms; F = %f, p = %f).\n'], ...
    mean(IT_target_RTs(:)), sem(IT_target_RTs(:)), ...
    mean(IT_nontarget_RTs(:)), sem(IT_nontarget_RTs(:)), ...
    table{2,6}, p(1));

% Third task accuracy -- targets over time
IT_RT_targets_first = IT_target_RTs(:, 1);
IT_RT_targets_last = IT_target_RTs(:, blocks);
[p, table] = anovan([IT_RT_targets_first; IT_RT_targets_last], {[ones(length(IT_RT_targets_first), 1); zeros(length(IT_RT_targets_last), 1)]}, 'model','full', 'display', 'off');
fprintf(['RTs were relatively stable over time for items that were previously PM targets. ', ...
    '(%.2f +- %.2f ms in the first block vs. %.2f +- %.2f ms in the last block, F = %f, p = %f).\n'], ...
    mean(IT_RT_targets_first), sem(IT_RT_targets_first), ...
    mean(IT_RT_targets_last), sem(IT_RT_targets_last), ...
    table{2,6}, p(1));



fprintf('\n');
